config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  devise_for :users, controllers: {
  omniauth_callbacks: 'users/omniauth_callbacks'
}

  resources :users, only: [:show, :edit, :update] do
    resources :likes, only: :index
  end
  resources :articles do
    resources :stocks, only: [ :create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :likers, only: :index
  end
  resources :stocks, only: :index

end

app/models/article.rb
class Article < ActiveRecord::Base

  belongs_to :user
  has_many :stocks, dependent: :destroy
  has_many :likes, dependent: :destroy

  def stocked_user?(user)
   stocks.find_by(user_id: user)
  end

  def liked_user?(user)
   likes.find_by(user_id: user)
  end

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

  def liked_user?(user)
   likes.find_by(user_id: user)
  end
end

app/models/liker.rb
class Liker < ActiveRecord::Base

  has_many :likes
  belongs_to :article

end

app/models/stock.rb
class Stock < ActiveRecord::Base

  belongs_to :user
  belongs_to :article

  def stocked_user?(user)
   stocks.find_by(user_id: user)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :authentication_keys => [:login]
  has_many :articles
  has_many :comments
  has_many :stocks
  has_many :likes
  validates :username, :email, :password, presence: true

  mount_uploader :avatar, AvatarUploader

  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20],
        username: auth.info.nickname,
        avatar: auth.info.image
      )
    end

    user
  end

  private
  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    '/users/sign_in' # サインアウト後のリダイレクト先URL
  end

  protected
  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :move_to_index, except: :index
  before_action :authenticate_user!, only: :new
  before_action :set_article, only: [:edit, :show, :update, :destroy]

  def index
    @articles = Article.order(created_at: :desc).page(params[:page]).per(20).includes(:user)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path, notice: '保存しました'
    else
      render :new
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  def show
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    @html = markdown.render(@article.text)
    @stock = @article.stocks.find_by(user_id: current_user.id)
    @like = @article.likes.find_by(user_id: current_user.id)
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "編集が成功しました"
      redirect_to root_path
    else
      flash[:notice] = "入力内容が正しくありません"
      render :edit
    end
  end

  private
  def move_to_index
    redirect_to new_user_session_path unless user_signed_in?
  end

  def article_params
    params.require(:article).permit(:title, :text).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/controllers/likers_controller.rb
class LikersController < ApplicationController

  def index
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @likes = Likes.where(user_id: current_user.id).order("created_at DESC").page(params[:page]).per(10)
  end

  def create
    @like = Like.create(user_id: current_user.id, article_id: params[:article_id])
    @likes = Like.where(article_id: params[:article_id])
    @article = Article.find(params[:article_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, article_id: params[:article_id])
    like.destroy
    @likes = Like.where(article_id: params[:article_id])
    @article = Article.find(params[:article_id])
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def index
    @stocks = Stock.where(user_id: current_user.id).order("created_at DESC").page(params[:page]).per(10)
  end

  def create
    @stock = Stock.create(user_id: current_user.id, article_id: params[:article_id])
    @stocks = Stock.where(article_id: params[:article_id])
    @article = Article.find(params[:article_id])
  end

  def destroy
    stock = Stock.find_by(user_id: current_user.id, article_id: params[:article_id])
    stock.destroy
    @stocks = Stock.where(article_id: params[:article_id])
    @article = Article.find(params[:article_id])
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # include Devise::Controllers::Rememberable

  def twitter
    callback_from :twitter
  end

  def github
    callback_from :github
  end

  private
  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      unless provider == 'twitter'
        session["devise.#{provider}_data"] = request.env['omniauth.auth']
      else
        session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      end
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update]

  def show
  end

  def edit
  end

  def update
    if @user.update(update_params)
      bypass_sign_in @user
      redirect_to edit_user_path(current_user)
    else
      render :edit
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def update_params
    params.require(:user).permit(:id, :username, :email, :email_checked, :password, :firstname, :lastname, :website, :company, :residence, :profile, :facebook_id, :linkedin_id, :google_plus_id, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/show.html.erb
<%= render "layouts/header" %>
<div id="main">
  <ol class="item-breadcrumbs" itemscope itemtype="http://schema.org/BreadcrumbList">
    <li itemprop="item-list-element" itemscope itemtype="http://schema.org/ListItem">
      <a itemprop="item" href="/">
        <span itemprop="name">Qiita</span>
      </a>
      <meta content="1" itemprop="position">
    </li>
    <li itemprop="item-list-element" itemscope itemtype="http://schema.org/ListItem">
      <a itemprop="item" href="#">
        <span itemprop="name">投稿</span>
      </a>
      <meta content="2" itemprop="position">
    </li>
    <li itemprop="item-list-element" itemscope itemtype="http://schema.org/ListItem">
      <a itemprop="item" href="#">
        <span itemprop="name">Android</span>
      </a>
      <meta content="3" itemprop="position">
    </li>
  </ol>
  <article itemscope itemtype="http://schema.org/Article">
    <div class="article-main-header">
      <div class="container">
      </div>
      <div class="container">
        <div class="row s-flex-align-center">
          <div class="col-sm-9">
            <h1 class="article-main-header__title">
              <%= @article.title %>
            </h1>
            <ul class="Tag-list">
              <li class="Tag-list__item" data-count="登録タグ数">
                <a class="u-link-unstyled Tag-list__label" href="#">
                  <img alt="タグ名1" class="Tag-list__icon" src="#">
                  <span>タグ名1</span>
                </a>
              </li>
              <li class="Tag-list__item" data-count="登録タグ数">
                <a class="u-link-unstyled Tag-list__label" href="#">
                  <img alt="タグ名2" class="Tag-list__icon" src="#">
                  <span>タグ名2</span>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-sm-3 js-like-and-comment-button">
            <%= render partial: "likes/like_and_comment_button", locals: { article: @article, like: @like } %>
          </div>
        </div>
      </div>
    </div>
    <div class="article-aside-header">
      <div class="container">
        <div class="u-flex u-space-between">
          <div class="u-flex u-flex-wrap">
            <div class="u-flex u-align-center s-pdv-5 u-flex-wrap">
              <div class="article-aside-header__author">
                <%= link_to user_path(@article.user_id) do %>
                  <%= image_tag @article.user.avatar, class: "thumb thumb--xs"%>
                <% end %>
                <%= link_to "#{@article.user.username}", user_path(@article.user_id), class: "u-link-unstylee" %>
              </div>
              <div class="article-aside-header__date">
                <span>
                  <%= @article.created_at.strftime('%Y/%m/%d') %>
                  に投稿
                </span>
              </div>
            </div>
            <% if @article.user_id == current_user.id %>
              <div class="u-flex u-align-center s-pdv-5 mobile-hidden">
                <%= link_to edit_article_path(@article.id), class: "article-aside-header__edit btn btn-default btn-xs" do %>
                  <span class="fa fa-pencil"></span>
                  投稿を編集
                <% end %>
              </div>
            <% end %>
<!--             <div class="u-flex u-align-center s-pdv-5 mobilehidden"></div>
            コメント、更新などがあった場合ここに表示する機能を付ける -->
          </div>
          <div class="u-flex u-align-center s-flex-justiry-between s-pdv-5 u-shrink-0">
            <div class="article-aside-header__stock">
              <div class="js-stock-button-<%= @article.id %> js-stockbutton" data-position="top" data-props={"stock_status":false}>
                <%= render partial: "stocks/stock_button", locals: { article: @article, stock: @stock } %>
              </div>
            </div>
            <div class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="fa fa-ellipsis-h fa-lg"></span>
              </a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li class="dropdown__item--mobile">
                  <a href="/username/articles/article.id.md">
                    <span class="fa fa-fw fa-history"></span>
                    編集履歴
                    <span>0</span>
                    <!-- 編集した回数を表示 -->
                  </a>
                </li>
                <li>
                  <a href="ここはuser.username/articles/ariticle.id.md">
                    <span class="fa fa-fw fa-file-text-o"></span>
                    Markdownで本文を見る
                  </a>
                </li>
                <li>
                  <a data-target=".js-report-form" data-toggle="modal" href="#">
                    <span class="fa fa-fw fa-flag"></span>
                    問題がある投稿を報告する
                  </a>
                </li>
                <% if @article.user_id == current_user.id %>
                  <li>
                    <%= link_to article_path(@article.id), method: :delete do %>
                      <span class="fa fa-fw fa-trash-o"></span>
                      削除
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row" id="article-body-wrapper" style="position: relative;">
        <div class="col-sm-9">
          <section class="markdown-content markdown-content-heading-enabled js-task-list-container clearfix position-relative" id="item-#{article.id}" itemprop="article-body">
            <%= @html.html_safe %>
          </section>
        </div>
        <div class="col-sm-3">
          <div class="social-buttons">
            <div class="social-buttons-twitter"></div>
            <div class="social-buttons_hatebu"></div>
            <div class="social-buttons_google-plus"></div>
            <div class="social-button_facebook"></div>
            <div class="social-buttons_pocket"></div>
          </div>
          <section class="items-show-author-info" itemprop="author" itemscope itemtype="http://schema.org/Person">
            <%= link_to user_path(@article.user_id) do %>
              <%= image_tag @article.user.avatar, class: "items-show-author-info_user-icon", itemprop: "image" %>
            <% end %>
            <div class="items-show-author-info_profile-stats">
              <strong class="items-show-author-info_user-name" itemprop="name">
                <%= link_to "#{@article.user.username}", user_path(@article.user_id), itemprop: "url" %>
              </strong>
              <div class="items-show-author-info_contribution">
                <span class="items-show-author-info_count">0</span>
                <span class="items-show-author-info_unit">Contribution</span>
              </div>
              <div data-react-class="T.user-follow-button" data-react-props="#">
                <span data-reactroot class="user-follow-button">
                  <button class="btn btn-default btn-block user-follow-button_inner btn-xs">
                    <i class="i fa fa-user-plus"></i>
                    <!-- react-text: 4 -->
                    フォロー
                    <!-- /react-text -->
                  </button>
                </span>
              </div>
            </div>
<!--             <section class="items-show-author-popular-items">
              <h5 class="items-show-author-popular-items_section-title">人気の投稿</h5>
              <ul class="items-show-author-popular-items_posts list-unstyled">
                <li itemscope itemtype="http://schema.org/Article">
                  <a itemprop="url" track="click" data-label="author-popular-items-at-sidebar" href="/user.username/arricles/article.id">ここは記事のタイトル</a>
                </li>
                <li itemscope itemtype="http://schema.org/Article">
                  <a itemprop="url" track="click" data-label="author-popular-items-at-sidebar" href="/user.username/arricles/article.id">ここは記事のタイトル</a>
                </li>
                <li itemscope itemtype="http://schema.org/Article">
                  <a itemprop="url" track="click" data-label="author-popular-items-at-sidebar" href="/user.username/arricles/article.id">ここは記事のタイトル</a>
                </li>
                <li itemscope itemtype="http://schema.org/Article">
                  <a itemprop="url" track="click" data-label="author-popular-items-at-sidebar" href="/user.username/arricles/article.id">ここは記事のタイトル</a>
                </li>
                <li itemscope itemtype="http://schema.org/Article">
                  <a itemprop="url" track="click" data-label="author-popular-items-at-sidebar" href="/user.username/arricles/article.id">ここは記事のタイトル</a>
                </li>
              </ul>
            </section>
            人気の定義(アルゴリズム)をどうしてるかは不明だけど、投稿者が投稿した全記事の中で、ストック数やいいね数に応じて上から順に5件記事を表示している -->
          </section>
          <div class="scroll-chaser"></div>
          <!-- <div data-react-class="T.Toc">
            <div data-reactroot class="tac-tree" style="width: 270px; position: relative; top: 0px;">
              <div class="toc-tree_contents nav" style="max-height: 429px">
                <ul>
                  <li class="">
                  現在スクロールしてる場所にactiveクラスが付くようにする
                    <a href="#">
                    記事中の見出しの場所へジャンプできるようにする
                  </li>
                  ここにリストを見出し数分作る
                </ul>
              </div>
            </div>
          </div>
          おそらく"#"によって見出し化された部分を、reactでscroll-chaserとして実装している -->
        </div>
      </div>
      <div class="row">
        <div class="col-sm-9">
          <div class="article-footer__menu">
            <div class="s-flex-align-center">
              <div class="js-likebutton" data-props="#">
                <div data-reactroot class="like-button">
                  <button class="p-button">
                    <span class="fa fa-fw fa-thumbs-up"></span>
                    <span>いいね</span>
                  </button>
                  <div class="like-button__balloon">
                    0
                    <!-- いいねの数を表示 -->
                  </div>
                </div>
              </div>
              <div class="article-footer__user-list">
                <div class="article-footer__user">
                  <div class="js-hovercard" data-hovercard-target-name="ここはusername">
                    <a itemprop="url" href="ここもusername">
                      <img alt="ここもusername" class="thumb thumb--xs" src="ここは@article.user.avatar">
                    </a>
                  </div>
                </div>
                <!-- article-footer__userをいいねした人数分表示。10人を超える場合はlikerページへのリンクを出す -->
              </div>
            </div>
            <div class="u-flex u-align-center">
              <div class="article-footer__stock">
                <div class="js-stock-button-<%= @article.id %> js-stockbutton" data-position="footer_menu" data-props="{"stock_status":false}">
                  <%= render partial: "stocks/stock_button", locals: { article: @article, stock: @stock } %>
                </div>
              </div>
              <div class="article-footer__edit-request">
                <a class="u-link-no-under-line" data-toggle="tooltip" title href="ここは/user/articles/article.id/edit" data-original-title="投稿者に記事をより良くするための提案ができます 💪">
                  <span class="fa fa-send-o fa-lg"></span>
                  <span>編集リクエスト</span>
                </a>
              </div>
              <div class="dropdown article-footer__dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <span class="fa fa-ellipsis-h"></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li>
                    <a href="ここは/user.username/articles/article.id/md">
                      <span class="fa fa-fw fa-file-text-o"></span>
                      Markdownで本文を見る
                    </a>
                  </li>
                  <li>
                    <a data-torget=".js-report-form" data-toggle="modal" href="#">
                      <i class="fa fa-fw fa-flag"></i>
                      問題がある投稿を報告する
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div class="items-show-body_article-column-footer">
            <div class="social-buttons">
              <div class="social-buttons_twitter">
                <!-- ここにシェアボタンを設置する -->
              </div>
              <div class="social-buttons_hatebu">
                <!-- ここにシェアボタンを設置する -->
              </div>
              <div class="social-buttons_google-plus">
                <!-- ここにシェアボタンを設置する -->
              </div>
              <div class="social-buttons_facebook">
                <!-- ここにシェアボタンを設置する -->
              </div>
              <div class="social-buttons_pocket">
                <!-- ここにシェアボタンを設置する -->
              </div>
            </div>
            <div class="items-show-comment_wrapper" id="comments">
              <!-- ここにコメント機能を付ける -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </article>
</div>

<!-- ここにはモーダルで問題報告とかの機能が入る -->

<%= render "layouts/footer" %>

app/views/layouts/_header.html.erb
<div class="header-container header-container-public" role="navigation">
  <div data-react-class="T.HeaderContainer" data-react-props="{"user":{"profile_image_url":"https://qiita-image-store.s3.amazonaws.com/0/136530/profile-images/1473719981","team_only":false,"teams":[],"url_name":"marshmallow0319"},"team":null,"news":{"type":"News","content":"ストックの他に「いいね」が追加されました","url":"http://blog.qiita.com/post/153200849029/qiita-like-button"},"initial_unread_count":0,"siteid_image":"http://cdn.qiita.com/siteid-reverse.png","is_team_page":false,"on_team_setting":false,"show_post_menu":true,"show_search_menu":true,"is_fluid":false,"locale":"ja"}">
    <header data-reactroot class="shared-header shared-header-public">
      <div class="shared-header_inner">
        <div class="shared-header_left">
          <span class="shared-header_logo open">
            <%= link_to root_path, class: "shared-header_logo_main" do%>
              <span class="shared-header_logo_figure">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 75 26">
                  <title>Qiita</title>
                  <path d="M24.6 12.2C24.6 6.2 20 0 12.2 0 6.2 0 0 4.6 0 12.4c0 6 4.6 12.2 12.4 12.2 2.5 0 5-.8 7.1-2.3l3.6 3.6 1.6-1.6-3.4-3.4c2.1-2.3 3.3-5.3 3.3-8.7zm-12.4-10c5.7 0 10.2 4.4 10.2 10.1 0 4.9-3.8 10.1-10.1 10.1s-10.1-5.1-10.1-10c0-6.4 5.1-10.2 10-10.2zM30.5 7.1h2.1v17h-2.1zM31.5 4.8c-1 0-1.8-.8-1.8-1.8s.8-1.8 1.8-1.8 1.8.8 1.8 1.8-.8 1.8-1.8 1.8zM40 4.8c-1 0-1.8-.8-1.8-1.8S39 1.2 40 1.2s1.8.8 1.8 1.8S41 4.8 40 4.8zM39 7.1h2.1v17H39zM53.7 24.4c-3.9 0-6.2-3-6.2-6v-16h2.1v4.7H57v2.1h-7.4v9.3c0 1.9 1.5 3.9 4.1 3.9.7 0 1.4-.2 2-.6l.2-.1 1 1.8-.2.1c-.9.5-2 .8-3 .8zM67.6 24.5c-5.7 0-9.1-4.5-9.1-8.9 0-5.7 4.5-9.1 8.9-9.1 2.3 0 4.1.8 5.4 2.3V7.1h2.1v17h-2.1v-1.9c-1.2 1.5-3 2.3-5.2 2.3zm-.2-15.9c-3.4 0-6.8 2.6-6.8 7 0 3.4 2.6 6.8 7 6.8 2 0 4-.9 5.3-2.5v-8.8c-1.4-1.6-3.3-2.5-5.5-2.5z"></path>
                </svg>
              </span>
            <% end %>
          </span>
          <form class="navbar-form navbar-left search-form" action-"/search" method="get">
            <div class="search-form_query-wrapper">
              <input class="form-control search-form_query" placeholder="キーワードを入力" autocomplete="off" name="q" value style="width: 220px;">
              <div class="search-form_wise-search-button" style="visibility: visible;">
                <i class="fa fa-caret-down"></i>
              </div>
            </div>
          </form>
          <div class="navbar-text header-news hidden-xs hidden-sm">
            <div class="header-news_label label label-warning">News</div>
            <a class="navbar-link" target="_blank" href="#">
              ストックの他に「いいね」が追加されました
            </a>
          </div>
        </div>
        <div class="shared-header_right">
          <% if user_signed_in? %>
            <div class="shared-header_search-icon">
              <a data-tiggle="model" data-target="#js-search-model">
                <i class="fa fa-search"></i>
              </a>
            </div>
            <div class="shared-header_search-model in modal fade" aria-hidden="false" id="js-search-model">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-body">
                    <form action="/search" method="get">
                      <input type="hidden" name="sort" id="sort" value="rel">
                      <div class="row">
                        <div class="col-xs-9">
                          <input type="text" name="q" id="q" class="form-control">
                        </div>
                        <div class="col-xs-3">
                          <input type="submit" name="commit" value="Search" class="btn btn-default btn-sm">
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <div class="shared-header_new-item btn-group">
              <%= link_to new_article_path, class: "shared-header_new-item_btn shared-header_new-item_post btn" do %>
                <i class="fa fa-lg fa-edit"></i>
                <!-- react-text: 36 -->
                投稿する
                <!-- /react-text -->
              <% end %>
              <a class="shared-header_new-item_btn dropdown-toggle btn">
                <i class="fa fa-caret-down"></i>
                <span class="shared-header_new-item_xs-edit">
                  <i class="fa fa-edit"></i>
                </span>
              </a>
            </div>
            <div class="shared-header_stock-items">
              <%= link_to "ストック一覧", stocks_path %>
            </div>
            <div class="shared-header_stock-items_xs-stock">
              <a href="#" title="ストック一覧">
                <i class="fa fa-folder"></i>
              </a>
            </div>
            <div class="shared-header_notifications">
              <div class="global-notifications open active">
                <div class="global-notifications__surface">
                  <div class="global-notifications_count">
                    0
                  </div>
                </div>
              </div>
            </div>
            <div class="shared-header_user">
              <a class="shared-header_user_clickable" data-toggle="dropdown" href="#" aria-expanded="false">
                <%= image_tag current_user.avatar, class: "shared-header_user_image", size: "32x32" %>
              </a>
              <ul class="dropdown-menu shared-header_user_dropdown">
                <li>
                  <%= link_to user_path(current_user) do%>
                    <i class="fa fa-fw fa-user"></i>
                    <!-- react-text: 57 -->
                    マイページ
                    <!-- /react-text -->
                  <% end %>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-fw fa-cog"></i>
                    <!-- react-text: 61 -->
                    設定
                    <!-- /react-text -->
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-fw fa-question"></i>
                    <!-- react-text: 65 -->
                    ヘルプ
                    <!-- /react-text -->
                  </a>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa fa-fw fa-sign-out"></i>
                    ログアウト
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        <% else %>
          <div class="shared-header_register-user">
            <%= link_to "ユーザ登録", new_user_registration_path, class: "btn btn-warning navbar-btn navbar-right" %>
          </div>
          <div class="shared-header_login-user">
            <%= link_to "ログイン", new_user_session_path %>
          </div>
        <% end %>
      </div>
    </header>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qiita</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/layouts/articles/_mine_stream.html.erb
<div class="mine-stream">
  <form action="/search" class="stream_search-form" method="GET">
    <div>
      <input placeholder="自分の投稿の中から検索" class="stream_search-form_text-field js-stream_search-form_text-field">
      <button type="submit" class="btn stream_search-form_search-button">
        <i class="fa fa-search"></i>
      </button>
    </div>
    <input type="hidden" name="q" class="js-stream_search-form_search-query" value="user:ここにアカウント名">
  </form>
  <div>
    <div class="circle-loading">
      <p>読み込み中</p>
      <div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</div>

app/views/stocks/_stock_button.html.erb
<% if article.stocked_user?(current_user) %>
  <div data-reactroot class="stock-button stock-button--stocked">
    <%= button_to article_stock_path(article, stock), method: :delete, remote: true do %>
      <div class="stock-button__unstock">
        <div class="fa-stack">
          <span class="fa fa-folder fa-stack-1x"></span>
          <span class="fa fa-check fa-stack-1x fa-inverse">
        </div>
        <!-- react-text: 6 -->
        <!-- &nbsp; -->
        <!-- /react-text -->
        <span class="stock-button__label">ストック</span>
      </div>
    <% end %>
  </div>
<% else %>
  <div data-reactroot class="stock-button">
    <%= button_to article_stocks_path(article), remote: true do %>
      <div class="stock-button__stock">
        <div class="fa-stack">
          <span class="fa fa-folder-open fa-stack-1x unstock"></span>
        </div>
        <!-- react-text: 6 -->
        <!-- &nbsp; -->
        <!-- /react-text -->
        <span class="stock-button__label">ストック</span>
      </div>
    <% end %>
  </div>
<% end %>